[versions]
agp = "9.4.0"
androidx-appcompat = "1.8.0"
androidx-biometric = "1.1.0"
androidx-core = "1.19.0"
androidx-espresso = "3.7.0"
androidx-junit = "1.3.0"
androidx-lifecycle = "2.11.0"
androidx-localbroadcast = "1.1.0"
androidx-preference = "1.2.1"
androidx-rules = "1.7.0"
androidx-runner = "1.7.0"
androidx-window = "1.5.1"
coroutines = "1.11.0"
guardian-jtorctl = "0.4.9.12"
iptproxy = "5.5.1"
junit = "4.13.2"
kotlin-serialization = "2.4.20"
material = "1.14.0"
navigation-fragment-ktx = "2.10.1"
orchestrator = "1.6.1"
quickie = "1.12.0"
retrofit = "3.0.0"
rootbeer = "0.1.2"
screengrab = "2.1.1"
serialization = "1.11.0"
tor-android = "0.4.9.11"
upnp = "1.1.0"
version-catalog-update = "1.1.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidx-biometric" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-espresso" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-localbroadcast = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcast" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
androidx-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
guardian-jtorctl = { module = "info.guardianproject:jtorctl", version.ref = "guardian-jtorctl" }
iptproxy = { module = "com.netzarchitekten:IPtProxy", version.ref = "iptproxy" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
material3 = { module = "com.google.android.material:material", version.ref = "material" }
quickie = { module = "io.github.g00fy2.quickie:quickie-bundled", version.ref = "quickie" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
rootbeer-lib = { module = "com.scottyab:rootbeer-lib", version.ref = "rootbeer" }
screengrab = { module = "tools.fastlane:screengrab", version.ref = "screengrab" }
tor-android = { module = "info.guardianproject:tor-android", version.ref = "tor-android" }
upnp = { module = "com.netzarchitekten:upnp", version.ref = "upnp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
