# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# set SUPPLY_JSON_KEY_DATA before running, or do `. ~/.fastlane/bashrc`

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Build debug and test APK for screenshots"
    lane :build_for_screengrab do
      gradle(
        task: 'clean'
      )
      gradle(
        task: 'assemble',
        build_type: 'Debug'
      )
      gradle(
        task: 'assemble',
        build_type: 'AndroidTest'
      )
    end

=begin
platform :android do
  desc "Upload the app store metadata"
  lane :metadata do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
  lane :metadata_and_images do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
    )
  end
  desc "Build a debug APK"
  lane :debug do
     gradle(task: "clean assembleDebug")
  end
  desc "Build a release APK"
  lane :release do
     gradle(task: "clean assembleFullperm")
  end
lane :beta do
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(
    task: 'clean assembleFullperm',
    build_type: 'Release'
  )
    upload_to_play_store(track: 'beta')

  # ...
end
=end
end
